//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public Nullable<decimal> contactNo { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
